# Generated by Django 4.2 on 2023-04-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
