# Generated by Django 4.2 on 2023-04-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_alter_categoria_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatos',
            new_name='Contato',
        ),
    ]
